"""publish not nullable

Revision ID: 597a696f3ada
Revises: b7d58562f437
Create Date: 2021-11-21 11:25:05.004557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597a696f3ada'
down_revision = 'b7d58562f437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
