name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    environment:
      name: testing
    env:
      DATABASE: ${{secrets.DATABASE}}
      HOST: ${{secrets.HOST}}
      PASSWORD: ${{secrets.PASSWORD}}
      USER: ${{secrets.USER}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: test with pytest
        run: |
          pipenv run pytest
